FROM centos:7

LABEL author="cloudyan cloudcode@qq.com"
LABEL desc="centos7"

# WORKDIR ./

# COPY src dest
# dest 必须是绝对路径，如果是目录必须反斜线结尾
# 如果 src 为多个，则 dest 必须为目录 如果 dest 不存在，会自动创建
# 如果 src 为目录，则会递归复制内容，但不复制 src 目录本身 类似 cp -r src/* /dest

COPY index.html /data/
COPY test /data/
# COPY test /data/test/
